planning_pipelines:
  - ompl
default_planning_pipeline: ompl
ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  request_adapters: >-
    default_planner_request_adapters/AddTimeParameterization
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints
  start_state_max_bounds_error: 0.1
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarConfigDefault
planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.2
  RRTstarConfigDefault:
    type: geometric::RRTstar
    range: 0.2
    goal_bias: 0.05
    delay_collision_checking: 1
arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - RRTstarConfigDefault
